version: "3.9"

services:
  php-fpm:
    image: php:7.4.33-fpm
    container_name: chatgpt
    restart: always
#    ports:
#     - 9000:9000
    volumes:
     - ./my_php.ini:/etc/php7/conf.d/00_my.ini
     - /Users/hyz/box/chat1/www/chatgpt:/www
     - ./zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
  

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
     - 8000:80
    volumes:
     - /Users/hyz/box/chat1/www/chatgpt:/www
     - ./chatgpt-web.conf:/etc/nginx/conf.d/default.conf
  

networks:
    default:
       external: true
       name: app_net
